export const API_URL = "http://127.0.0.1:5000";

export const categoryList = [
  "Accessories",
  "Actors/actresses",
  "Adult content",
  "Animals",
  "Art",
  "Artists",
  "Beauty",
  "Business",
  "Careers",
  "Cars",
  "Cinema",
  "Clothing",
  "Coaches",
  "Comics sketches",
  "Computers",
  "Economics",
  "Extreme",
  "Family",
  "Fashion",
  "Finance",
  "Fitness",
  "Fun",
  "Gadgets",
  "Gym",
  "Happiness",
  "Humor",
  "Jewellery",
  "Journalism",
  "Kids",
  "Lifestyle",
  "Literature",
  "Luxury",
  "Machinery",
  "Modeling",
  "Motorbikes",
  "Music",
  "Nature landscapes",
  "Outdoor activity",
  "Outfits",
  "Photography",
  "Racing",
  "Retail",
  "Science",
  "Shopping",
  "Shows",
  "Sports with a ball",
  "Sports",
  "Technologies",
  "Toys",
  "Travel",
];
